export const games = [
    {
        id: "pubg-mobile",
        title: "PUBG Mobile",
        genre: "Battle Royale",
        platform: "Mobile",
        releaseDate: "2018-03-19",
        rating: "4.8/5",
        ratingScore: 4.8,
        status: "Trending",
        image: "assests/images/games/pubg.jpg",
        description: "A battle royale game where players compete to be the last one standing. It is known for team strategy, survival gameplay, and intense matches.",
        bestFor: "Competitive players and squad teamwork",
        difficulty: "Medium",
        whyPlay: "Great for players who enjoy survival, fast decisions, and team-based action."
    },
    {
        id: "fortnite",
        title: "Fortnite",
        genre: "Battle Royale",
        platform: "PC, Console, Mobile",
        releaseDate: "2017-07-21",
        rating: "4.6/5",
        ratingScore: 4.6,
        status: "Trending",
        image: "assests/images/games/fortnite.jpg",
        description: "A colorful battle royale game that combines shooting, building, events, and creative gameplay modes.",
        bestFor: "Creative and competitive players",
        difficulty: "Medium",
        whyPlay: "Perfect if you like colorful visuals, live events, building mechanics, and fast battle royale matches."
    },
    {
        id: "minecraft",
        title: "Minecraft",
        genre: "Sandbox",
        platform: "PC, Console, Mobile",
        releaseDate: "2011-11-18",
        rating: "4.9/5",
        ratingScore: 4.9,
        status: "Top Rated",
        image: "assests/images/games/minecraft.avif",
        description: "A sandbox game focused on building, crafting, survival, and creativity in an open block-based world.",
        bestFor: "Creative players and builders",
        difficulty: "Easy",
        whyPlay: "A great choice for relaxing, building, exploring, and creating your own world."
    },
    {
        id: "valorant",
        title: "Valorant",
        genre: "FPS",
        platform: "PC",
        releaseDate: "2020-06-02",
        rating: "4.7/5",
        ratingScore: 4.7,
        status: "Top Rated",
        image: "assests/images/games/valorant.webp",
        description: "A tactical first-person shooter where teams use aim, strategy, and agent abilities to win rounds.",
        bestFor: "Tactical FPS players",
        difficulty: "Hard",
        whyPlay: "Best for players who enjoy precise aim, competitive teamwork, and strategic abilities."
    },
    {
        id: "genshin-impact",
        title: "Genshin Impact",
        genre: "RPG",
        platform: "PC, Console, Mobile",
        releaseDate: "2020-09-28",
        rating: "4.6/5",
        ratingScore: 4.6,
        status: "Trending",
        image: "assests/images/games/genshin.avif",
        description: "An open-world RPG with exploration, character collection, quests, and elemental combat.",
        bestFor: "Story and exploration lovers",
        difficulty: "Easy",
        whyPlay: "Great for players who enjoy open worlds, beautiful environments, quests, and character collection."
    },
    {
        id: "roblox",
        title: "Roblox",
        genre: "Sandbox",
        platform: "PC, Console, Mobile",
        releaseDate: "2006-09-01",
        rating: "4.4/5",
        ratingScore: 4.4,
        status: "Popular",
        image: "assests/images/games/roblox.jpg",
        description: "A platform where users can play and create different games, worlds, and social experiences.",
        bestFor: "Casual players and creators",
        difficulty: "Easy",
        whyPlay: "Ideal for trying many mini-games, social experiences, and creative user-generated worlds."
    },
    {
        id: "call-of-duty-warzone",
        title: "Call of Duty: Warzone",
        genre: "Battle Royale",
        platform: "PC, Console",
        releaseDate: "2020-03-10",
        rating: "4.5/5",
        ratingScore: 4.5,
        status: "Popular",
        image: "assests/images/games/warzone.avif",
        description: "A fast-paced battle royale shooter with realistic weapons, squads, contracts, and tactical combat.",
        bestFor: "Action and shooter fans",
        difficulty: "Hard",
        whyPlay: "Recommended for players who enjoy realistic gunplay, intense fights, and squad-based battle royale gameplay."
    },
    {
        id: "the-last-of-us",
        title: "The Last of Us",
        genre: "Adventure",
        platform: "Console, PC",
        releaseDate: "2013-06-14",
        rating: "4.9/5",
        ratingScore: 4.9,
        status: "Top Rated",
        image: "assests/images/games/lastofus.avif",
        description: "A story-driven adventure game focused on survival, emotional storytelling, and cinematic gameplay.",
        bestFor: "Story-driven players",
        difficulty: "Medium",
        whyPlay: "Perfect if you want emotional storytelling, cinematic gameplay, and survival adventure."
    },
    {
        id: "elden-ring",
        title: "Elden Ring",
        genre: "RPG",
        platform: "PC, Console",
        releaseDate: "2022-02-25",
        rating: "4.9/5",
        ratingScore: 4.9,
        status: "Top Rated",
        image: "assests/images/games/eldenring.jpg",
        description: "A fantasy action RPG with open-world exploration, challenging combat, and deep character progression.",
        bestFor: "Challenge seekers and RPG fans",
        difficulty: "Hard",
        whyPlay: "Best for players who enjoy deep exploration, fantasy worlds, and rewarding difficult combat."
    },
    {
        id: "among-us",
        title: "Among Us",
        genre: "Social Deduction",
        platform: "PC, Console, Mobile",
        releaseDate: "2018-06-15",
        rating: "4.3/5",
        ratingScore: 4.3,
        status: "Popular",
        image: "assests/images/games/amongus.jpg",
        description: "A multiplayer social deduction game where crewmates complete tasks while impostors secretly eliminate them.",
        bestFor: "Friends and casual groups",
        difficulty: "Easy",
        whyPlay: "Fun for social play, teamwork, deception, and quick matches with friends."
    },
            {
        id: "grand-theft-auto-vi",
        title: "Grand Theft Auto VI",
        genre: "Action Adventure",
        platform: "PS5, Xbox Series X/S",
        releaseDate: "Nov 19, 2026",
        rating: "Coming Soon",
        ratingScore: 0,
        status: "Coming Soon",
image: "assests/images/games/gta6.webp",
        description: "An upcoming open-world action-adventure game from Rockstar Games.",
        bestFor: "Open-world and story-driven action fans",
        difficulty: "Unknown",
        whyPlay: "One of the most anticipated upcoming games in the world."
    },
    {
        id: "007-first-light",
        title: "007 First Light",
        genre: "Action Adventure",
        platform: "PS5, Xbox Series X/S, PC, Switch 2",
        releaseDate: "May 27, 2026",
        rating: "Coming Soon",
        ratingScore: 0,
        status: "Coming Soon",
image: "assests/images/games/007-first-light.avif",
        description: "An upcoming James Bond origin story game developed by IO Interactive.",
        bestFor: "Spy action and cinematic adventure fans",
        difficulty: "Unknown",
        whyPlay: "A fresh Bond story from the creators of Hitman."
    },
    {
        id: "arknights-endfield",
        title: "Arknights: Endfield",
        genre: "RPG",
        platform: "PC, PS5, iOS, Android",
        releaseDate: "Jan 22, 2026",
        rating: "Coming Soon",
        ratingScore: 0,
        status: "Coming Soon",
image: "assests/images/games/arknights-endfield.avif",        description: "An upcoming free-to-play RPG with exploration, strategy, and sci-fi world-building.",
        bestFor: "Anime RPG and strategy fans",
        difficulty: "Medium",
        whyPlay: "A strong upcoming pick for players who enjoy RPG worlds and tactical gameplay."
    },
    {
        id: "pokemon-champions",
        title: "Pokémon Champions",
        genre: "Strategy",
        platform: "iOS, Android, Switch",
        releaseDate: "2026",
        rating: "Coming Soon",
        ratingScore: 0,
        status: "Coming Soon",
image: "assests/images/games/pokemon-champions.jpg",        description: "An upcoming Pokémon battle-focused game for mobile and Nintendo platforms.",
        bestFor: "Pokémon and competitive battle fans",
        difficulty: "Easy",
        whyPlay: "A good upcoming mobile-friendly title for Pokémon players."
    },
    {
        id: "marvels-wolverine",
        title: "Marvel's Wolverine",
        genre: "Action",
        platform: "PS5",
        releaseDate: "2026",
        rating: "Coming Soon",
        ratingScore: 0,
        status: "Coming Soon",
image: "assests/images/games/wolverine.jpeg",        description: "An upcoming action game starring Wolverine, developed by Insomniac Games.",
        bestFor: "Marvel and action fans",
        difficulty: "Unknown",
        whyPlay: "A major upcoming PlayStation title for superhero game fans."
    },
    {
    id: "hay-day",
    title: "Hay Day",
    genre: "Casual",
    platform: "iOS, Android, Mobile",
    releaseDate: "2012-06-21",
    rating: "4.7/5",
    ratingScore: 4.7,
    status: "Popular",
    image: "assests/images/games/hayday.jpg",
    description: "A relaxing farming game where players build farms, trade goods, and manage animals.",
    bestFor: "Casual and relaxing gameplay",
    difficulty: "Easy",
    whyPlay: "Perfect for relaxing sessions and cozy farming gameplay."
},
{
    id: "candy-crush",
    title: "Candy Crush Saga",
    genre: "Puzzle",
    platform: "iOS, Android, Mobile",
    releaseDate: "2012-04-12",
    rating: "4.5/5",
    ratingScore: 4.5,
    status: "Popular",
    image: "assests/images/games/candycrush.jpg",
    description: "A famous puzzle game focused on matching candies and completing levels.",
    bestFor: "Puzzle and casual players",
    difficulty: "Easy",
    whyPlay: "Great for quick fun sessions and relaxing puzzle gameplay."
},
{
    id: "clash-of-clans",
    title: "Clash of Clans",
    genre: "Strategy",
    platform: "iOS, Android, Mobile",
    releaseDate: "2012-08-02",
    rating: "4.8/5",
    ratingScore: 4.8,
    status: "Top Rated",
    image: "assests/images/games/coc.jpg",
    description: "A strategy game where players build villages, join clans, and battle others.",
    bestFor: "Strategy and teamwork lovers",
    difficulty: "Medium",
    whyPlay: "Excellent for competitive strategy and long-term progression."
},
{
    id: "clash-royale",
    title: "Clash Royale",
    genre: "Strategy",
    platform: "iOS, Android, Mobile",
    releaseDate: "2016-03-02",
    rating: "4.6/5",
    ratingScore: 4.6,
    status: "Popular",
    image: "assests/images/games/clashroyale.jpg",
    description: "A fast-paced multiplayer strategy game using cards and tower battles.",
    bestFor: "Competitive mobile players",
    difficulty: "Medium",
    whyPlay: "Fun for quick online matches and strategy battles."
},
{
    id: "subway-surfers",
    title: "Subway Surfers",
    genre: "Endless Runner",
    platform: "iOS, Android, Mobile",
    releaseDate: "2012-05-24",
    rating: "4.5/5",
    ratingScore: 4.5,
    status: "Popular",
    image: "assests/images/games/subway.jpg",
    description: "An endless runner game where players dodge trains and collect coins.",
    bestFor: "Quick mobile gaming",
    difficulty: "Easy",
    whyPlay: "A classic fast-paced game for short fun sessions."
},
{
    id: "monopoly-go",
    title: "MONOPOLY GO!",
    genre: "Casual",
    platform: "iOS, Android, Mobile",
    releaseDate: "2023-04-11",
    rating: "4.4/5",
    ratingScore: 4.4,
    status: "Trending",
    image: "assests/images/games/monopolygo.jpg",
    description: "A modern mobile version of Monopoly with multiplayer events and rewards.",
    bestFor: "Social and casual players",
    difficulty: "Easy",
    whyPlay: "Great for social gameplay and daily progression."
},
{
    id: "sudoku",
    title: "Sudoku.com",
    genre: "Puzzle",
    platform: "iOS, Android, Mobile",
    releaseDate: "2017-01-10",
    rating: "4.6/5",
    ratingScore: 4.6,
    status: "Popular",
    image: "assests/images/games/sudoku.jpg",
    description: "A classic number puzzle game focused on logic and concentration.",
    bestFor: "Brain training and puzzle lovers",
    difficulty: "Medium",
    whyPlay: "Perfect for improving focus and logical thinking."
},
{
    id: "brain-test",
    title: "Brain Test",
    genre: "Puzzle",
    platform: "iOS, Android, Mobile",
    releaseDate: "2019-01-01",
    rating: "4.5/5",
    ratingScore: 4.5,
    status: "Popular",
    image: "assests/images/games/braintest.jpg",
    description: "A tricky puzzle game filled with riddles and brain teasers.",
    bestFor: "Puzzle and smart thinking fans",
    difficulty: "Medium",
    whyPlay: "Fun for testing creativity and problem-solving skills."
},
{
    id: "8-ball-pool",
    title: "8 Ball Pool",
    genre: "Sports",
    platform: "iOS, Android, Mobile",
    releaseDate: "2013-01-01",
    rating: "4.5/5",
    ratingScore: 4.5,
    status: "Popular",
    image: "assests/images/games/8ballpool.jpg",
    description: "A multiplayer pool game with online matches and tournaments.",
    bestFor: "Competitive casual players",
    difficulty: "Easy",
    whyPlay: "Perfect for quick online matches with friends."
},
{
    id: "royal-match",
    title: "Royal Match",
    genre: "Puzzle",
    platform: "iOS, Android, Mobile",
    releaseDate: "2021-02-25",
    rating: "4.7/5",
    ratingScore: 4.7,
    status: "Trending",
    image: "assests/images/games/royalmatch.jpg",
    description: "A colorful match puzzle game with castle upgrades and events.",
    bestFor: "Relaxing puzzle gameplay",
    difficulty: "Easy",
    whyPlay: "One of the most popular mobile puzzle games right now."
}
];