export const games = [
    {
        id: "pubg-mobile",
        title: "PUBG Mobile",
        genre: "Battle Royale",
        platform: "Mobile",
        releaseDate: "2018-03-19",
        rating: "4.8/5",
        ratingScore: 4.8,
        status: "Trending",
        image: "assests/images/games/pubg.jpg",
        description: "A battle royale game where players compete to be the last one standing. It is known for team strategy, survival gameplay, and intense matches."
    },
    {
        id: "fortnite",
        title: "Fortnite",
        genre: "Battle Royale",
        platform: "PC, Console, Mobile",
        releaseDate: "2017-07-21",
        rating: "4.6/5",
        ratingScore: 4.6,
        status: "Trending",
        image: "assests/images/games/fortnite.jpg",
        description: "A colorful battle royale game that combines shooting, building, events, and creative gameplay modes."
    },
    {
        id: "minecraft",
        title: "Minecraft",
        genre: "Sandbox",
        platform: "PC, Console, Mobile",
        releaseDate: "2011-11-18",
        rating: "4.9/5",
        ratingScore: 4.9,
        status: "Top Rated",
        image: "assests/images/games/minecraft.avif",
        description: "A sandbox game focused on building, crafting, survival, and creativity in an open block-based world."
    },
    {
        id: "valorant",
        title: "Valorant",
        genre: "FPS",
        platform: "PC",
        releaseDate: "2020-06-02",
        rating: "4.7/5",
        ratingScore: 4.7,
        status: "Top Rated",
        image: "assests/images/games/valorant.webp",
        description: "A tactical first-person shooter where teams use aim, strategy, and agent abilities to win rounds."
    },
    {
        id: "genshin-impact",
        title: "Genshin Impact",
        genre: "RPG",
        platform: "PC, Console, Mobile",
        releaseDate: "2020-09-28",
        rating: "4.6/5",
        ratingScore: 4.6,
        status: "Trending",
        image: "assests/images/games/genshin.avif",
        description: "An open-world RPG with exploration, character collection, quests, and elemental combat."
    },
    {
        id: "roblox",
        title: "Roblox",
        genre: "Sandbox",
        platform: "PC, Console, Mobile",
        releaseDate: "2006-09-01",
        rating: "4.4/5",
        ratingScore: 4.4,
        status: "Popular",
        image: "assests/images/games/roblox.jpg",
        description: "A platform where users can play and create different games, worlds, and social experiences."
    },
    {
        id: "call-of-duty-warzone",
        title: "Call of Duty: Warzone",
        genre: "Battle Royale",
        platform: "PC, Console",
        releaseDate: "2020-03-10",
        rating: "4.5/5",
        ratingScore: 4.5,
        status: "Popular",
        image: "assests/images/games/warzone.avif",
        description: "A fast-paced battle royale shooter with realistic weapons, squads, contracts, and tactical combat."
    },
    {
        id: "the-last-of-us",
        title: "The Last of Us",
        genre: "Adventure",
        platform: "Console, PC",
        releaseDate: "2013-06-14",
        rating: "4.9/5",
        ratingScore: 4.9,
        status: "Top Rated",
        image: "assests/images/games/lastofus.avif",
        description: "A story-driven adventure game focused on survival, emotional storytelling, and cinematic gameplay."
    },
    {
        id: "elden-ring",
        title: "Elden Ring",
        genre: "RPG",
        platform: "PC, Console",
        releaseDate: "2022-02-25",
        rating: "4.9/5",
        ratingScore: 4.9,
        status: "Top Rated",
        image: "assests/images/games/eldenring.jpg",
        description: "A fantasy action RPG with open-world exploration, challenging combat, and deep character progression."
    },
    {
        id: "among-us",
        title: "Among Us",
        genre: "Social Deduction",
        platform: "PC, Console, Mobile",
        releaseDate: "2018-06-15",
        rating: "4.3/5",
        ratingScore: 4.3,
        status: "Popular",
        image: "assests/images/games/amongus.jpg",
        description: "A multiplayer social deduction game where crewmates complete tasks while impostors secretly eliminate them."
    },
    {
        id: "retro-racer",
        title: "Retro Racer",
        genre: "Racing",
        platform: "PC, Console",
        releaseDate: "Dec 15, 2026",
        rating: "Coming Soon",
        ratingScore: 0,
        status: "Coming Soon",
        image: "assests/images/games/retro-racer.jpg",
        description: "A retro-inspired racing game with neon tracks, arcade-style controls, and fast-paced challenges."
    },
    {
        id: "neon-fighter",
        title: "Neon Fighter",
        genre: "Action",
        platform: "PC, Console",
        releaseDate: "Jan 2027",
        rating: "Coming Soon",
        ratingScore: 0,
        status: "Coming Soon",
        image: "assests/images/games/neon-fighter.jpg",
        description: "An upcoming action fighting game with futuristic visuals, neon arenas, and competitive battles."
    }
];